### ISSUE TITLE
Layout is weird

### ISSUE THREAD

**Issue by JulieVelghe** [cultuurnet/uitpas-voordelen-search#59]
Hello,
I've tried to get a clean install, but I'm running against some issues. When I try yarn install, I get a heap of warnings and errors. I can do a yarn start, however, the layout of the page seems messed up (missing filters?).

![image](https://github.com/cultuurnet/uitpas-voordelen-search/assets/46524074/61f4f43d-0c28-4d69-9dce-5883e2ce9015)

Also, when I want to add a systems checked to my div, the page doesn't load at all. I'm trying to add 'data-card-systems-checked="UiTPAS de Merode"'
![image](https://github.com/cultuurnet/uitpas-voordelen-search/assets/46524074/bc69e7db-0824-4068-b93a-54d4cc95ad5a)

**Comment by JulieVelghe** [comment]
Here is my warning stack:

`yarn install v1.22.21
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning node-sass-chokidar > chokidar > fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
warning react-scripts > fsevents@1.1.2: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
warning react-scripts > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2      
warning react-scripts > fsevents > node-pre-gyp@0.6.39: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning react-scripts > fsevents > node-pre-gyp > hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning react-scripts > fsevents > node-pre-gyp > request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > fsevents > node-pre-gyp > request > hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning react-scripts > fsevents > node-pre-gyp > tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
warning react-scripts > fsevents > node-pre-gyp > hawk > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to t
he latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > fsevents > node-pre-gyp > hawk > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to t
he latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > fsevents > node-pre-gyp > hawk > boom > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgra
de to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > fsevents > node-pre-gyp > hawk > sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning react-scripts > fsevents > node-pre-gyp > hawk > sntp > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgra
de to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > fsevents > node-pre-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning react-scripts > fsevents > node-pre-gyp > tar-pack > tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
warning react-scripts > fsevents > node-pre-gyp > hawk > cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade 
to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > fsevents > node-pre-gyp > hawk > cryptiles > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please 
upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > fsevents > node-pre-gyp > request > har-validator@4.2.1: this library is no longer supported
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/4] ⠈ waiting...
[2/4] ⠁ node-sass
[-/4] ⠁ waiting...
error C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@20.9.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python39\python.exe" in the PATH
gyp verb `which` succeeded C:\Python39\python.exe C:\Python39\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python39\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v3.8.0
`

**Comment by JulieVelghe** [comment]
Here are my warnings: 

`PS C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen> yarn install
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠂ node-sass
error C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.6.2
gyp info using node@20.9.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python39\python.exe" in the PATH
gyp verb `which` succeeded C:\Python39\python.exe C:\Python39\python.exe
gyp verb check python version `C:\Python39\python.exe -c "import platform; print(platform.python_version());"` returned: "3.9.1\r\n"
gyp verb could not find "C:\Python39\python.exe". checking python launcher
gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.18\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 20.9.0
gyp verb command install [ '20.9.0' ]
gyp verb install input version string "20.9.0"
gyp verb install installing version: 20.9.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 20.9.0
gyp verb build dir attempting to create "build" dir: C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\julie\\.node-gyp\\20.9.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\julie\\.node-gyp\\20.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\julie\\.node-gyp\\20.9.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2778, in Load
    variables, includes, depth, check, True)
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 394, in LoadTargetBuildFile
    includes, True, check)
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 266, in LoadOneBuildFile
    aux_data, includes, check)
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 303, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 246, in LoadOneBuildFile
    None)
  File "C:\Users\julie\.node-gyp\20.9.0\include\node\common.gypi", line 1
    nerate ',
            ^
SyntaxError: EOL while scanning string literal
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\julie\\Documents\\CabinetC\\Repos\\UitPasVoordelen\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\julie\Documents\CabinetC\Repos\UitPasVoordelen\node_modules\node-sass
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
`
